- internal/ydls/handler.go
With this PR, it is now possible to use something like this as the index template:
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Relax CSP demo</title>
</head>
<body>
<audio controls>
<source src="/ogg/https://youtu.be/dQw4w9WgXcQ" type="audio/ogg">
Your browser does not support the audio element.
</audio>
</body>
</html>
```
> Relax Content-Security-Policy for index page

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.01.08)
> Update youtube-dl from 2021.01.03 to 2021.01.08

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.01.16)
> Update youtube-dl from 2021.01.08 to 2021.01.16

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.01.24.1)
> Update youtube-dl from 2021.01.16 to 2021.01.24.1

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.02.04.1)
> Update youtube-dl from 2021.01.24.1 to 2021.02.04.1

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.02.10)
> Update youtube-dl from 2021.02.04.1 to 2021.02.10

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.02.22)
> Update youtube-dl from 2021.02.10 to 2021.02.22

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.02)
> Update youtube-dl from 2021.02.22 to 2021.03.02

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.03)
> Update youtube-dl from 2021.03.02 to 2021.03.03

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.14)
> Update youtube-dl from 2021.03.03 to 2021.03.14

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.25)
> Update youtube-dl from 2021.03.14 to 2021.03.25

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.03.31)
> Update youtube-dl from 2021.03.25 to 2021.03.31

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.01)
> Update youtube-dl from 2021.03.31 to 2021.04.01

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.07)
> Update youtube-dl from 2021.04.01 to 2021.04.07

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.17)
> Update youtube-dl from 2021.04.07 to 2021.04.17

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.26)
> Update youtube-dl from 2021.04.17 to 2021.04.26

- README.md
- _dev/markdown-formats.go
- internal/ydls/config_test.go
- internal/ydls/ydls.go
- ydls.json
Both librav1e and liboam-av1 seems to have problem when using pipe output, but libsvtav1
seem to work fine
librav1e fails: ffmpeg -v trace -hide_banner -y -f lavfi -i testsrc -c:v librav1e -t 100ms -f matroska pipe:1 > test.mkv
libaom-av1 segfault: ffmpeg -v trace -hide_banner -y -f lavfi -i testsrc -t 1s -c:v libaom-av1 -f null -
> Add av1 codec

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.05.16)
> Update youtube-dl from 2021.04.26 to 2021.05.16

- Dockerfile
[Release notes](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.06.06)
> Update youtube-dl from 2021.05.16 to 2021.06.06

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.11.10.1)
> Update yt-dlp from 2021.10.22 to 2021.11.10.1

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.12.01)
> Update yt-dlp from 2021.11.10.1 to 2021.12.01

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.12.25)
> Update yt-dlp from 2021.12.01 to 2021.12.25

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.12.27)
> Update yt-dlp from 2021.12.25 to 2021.12.27

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.01.21)
> Update yt-dlp from 2021.12.27 to 2022.01.21

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.02.04)
> Update yt-dlp from 2022.01.21 to 2022.02.04

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.03.08.1)
> Update yt-dlp from 2022.02.04 to 2022.03.08.1

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.04.08)
> Update yt-dlp from 2022.03.08.1 to 2022.04.08

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.05.18)
> Update yt-dlp from 2022.04.08 to 2022.05.18

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.06.22.1)
> Update yt-dlp from 2022.05.18 to 2022.06.22.1

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.06.29)
> Update yt-dlp from 2022.06.22.1 to 2022.06.29

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.07.18)
> Update yt-dlp from 2022.06.29 to 2022.07.18

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.08.08)
> Update yt-dlp from 2022.07.18 to 2022.08.08

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.08.14)
> Update yt-dlp from 2022.08.08 to 2022.08.14

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.08.19)
> Update yt-dlp from 2022.08.14 to 2022.08.19

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.09.01)
> Update yt-dlp from 2022.08.19 to 2022.09.01

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.10.04)
> Update yt-dlp to 2022.10.04 from 2022.09.01

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.11.11)
> Update yt-dlp to 2022.11.11 from 2022.10.04

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.01.02)
> Update yt-dlp to 2023.01.02 from 2022.11.11

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.01.06)
> Update yt-dlp to 2023.01.06 from 2023.01.02

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17)
> Update yt-dlp to 2023.02.17 from 2023.01.06

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.03)
> Update yt-dlp to 2023.03.03 from 2023.02.17

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04)
> Update yt-dlp to 2023.03.04 from 2023.03.03

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.06.22)
> Update yt-dlp to 2023.06.22 from 2023.03.04

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.07.06)
> Update yt-dlp to 2023.07.06 from 2023.06.22

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.09.24)
> Update yt-dlp to 2023.09.24 from 2023.07.06

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.07)
> Update yt-dlp to 2023.10.07 from 2023.09.24

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.13)
> Update yt-dlp to 2023.10.13 from 2023.10.07

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.14)
> Update yt-dlp to 2023.11.14 from 2023.10.13

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.11.16)
> Update yt-dlp to 2023.11.16 from 2023.11.14

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.12.30)
> Update yt-dlp to 2023.12.30 from 2023.11.16

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.03.10)
> Update yt-dlp to 2024.03.10 from 2023.12.30

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.05.26)
> Update yt-dlp to 2024.05.26 from 2024.04.09

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.05.27)
> Update yt-dlp to 2024.05.27 from 2024.05.26

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.01)
> Update yt-dlp to 2024.07.01 from 2024.05.27

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.02)
> Update yt-dlp to 2024.07.02 from 2024.07.01

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.09)
> Update yt-dlp to 2024.07.09 from 2024.07.07

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.16)
> Update yt-dlp to 2024.07.16 from 2024.07.09

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.25)
> Update yt-dlp to 2024.07.25 from 2024.07.16

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.01)
> Update yt-dlp to 2024.08.01 from 2024.07.25

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.06)
> Update yt-dlp to 2024.08.06 from 2024.08.01

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.09.27)
> Update yt-dlp to 2024.09.27 from 2024.08.06

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.07)
> Update yt-dlp to 2024.10.07 from 2024.09.27

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.10.22)
> Update yt-dlp to 2024.10.22 from 2024.10.07

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.04)
> Update yt-dlp to 2024.11.04 from 2024.10.22

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.11.18)
> Update yt-dlp to 2024.11.18 from 2024.11.04

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.03)
> Update yt-dlp to 2024.12.03 from 2024.11.18

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.06)
> Update yt-dlp to 2024.12.06 from 2024.12.03

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.23)
> Update yt-dlp to 2024.12.23 from 2024.12.13

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.12)
> Update yt-dlp to 2025.01.12 from 2024.12.23

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.01.26)
> Update yt-dlp to 2025.01.26 from 2025.01.15

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.02.19)
> Update yt-dlp to 2025.02.19 from 2025.01.26

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.21)
> Update yt-dlp to 2025.03.21 from 2025.02.19

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.25)
> Update yt-dlp to 2025.03.25 from 2025.03.21

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.26)
> Update yt-dlp to 2025.03.26 from 2025.03.25

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.27)
> Update yt-dlp to 2025.03.27 from 2025.03.26

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.03.31)
> Update yt-dlp to 2025.03.31 from 2025.03.27

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.04.30)
> Update yt-dlp to 2025.04.30 from 2025.03.31

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.05.22)
> Update yt-dlp to 2025.05.22 from 2025.04.30

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.09)
> Update yt-dlp to 2025.06.09 from 2025.05.22

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.06.25)
> Update yt-dlp to 2025.06.25 from 2025.06.09

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.07.21)
> Update yt-dlp to 2025.07.21 from 2025.06.30

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.08.27)
> Update yt-dlp to 2025.08.27 from 2025.08.22

- Dockerfile
[Release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2025.09.26)
> Update yt-dlp to 2025.09.26 from 2025.09.23
